pool:
  vmImage: 'windows-2019'

trigger:
- develop
- master

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.1.100'
  inputs:
    version: 3.1.100

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: SQLSchemaCompare
    verbose: false

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '.\SQLSchemaCompare.Test\SQLSchemaCompare.Test.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --filter Category!=IntegrationTest --collect "Code coverage"'

