//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLCompare.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLCompare.Services.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Now.
        /// </summary>
        public static string ButtonCompareNow {
            get {
                return ResourceManager.GetString("ButtonCompareNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string ButtonNewProject {
            get {
                return ResourceManager.GetString("ButtonNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string ButtonOpenProject {
            get {
                return ResourceManager.GetString("ButtonOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string ButtonPrev {
            get {
                return ResourceManager.GetString("ButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ButtonQuit {
            get {
                return ResourceManager.GetString("ButtonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update and restart.
        /// </summary>
        public static string ButtonUpdateAndRestart {
            get {
                return ResourceManager.GetString("ButtonUpdateAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked.
        /// </summary>
        public static string ErrorAccountLocked {
            get {
                return ResourceManager.GetString("ErrorAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact TiCodeX website:.
        /// </summary>
        public static string ErrorCannotContactTiCodeXWebsite {
            get {
                return ResourceManager.GetString("ErrorCannotContactTiCodeXWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not specified.
        /// </summary>
        public static string ErrorEmailNotSpecified {
            get {
                return ResourceManager.GetString("ErrorEmailNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not verified.
        /// </summary>
        public static string ErrorEmailNotVerified {
            get {
                return ResourceManager.GetString("ErrorEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ErrorInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the file: {0}.
        /// </summary>
        public static string ErrorLoadProject {
            get {
                return ResourceManager.GetString("ErrorLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load project file: file not found..
        /// </summary>
        public static string ErrorLoadProjectFileNotFound {
            get {
                return ResourceManager.GetString("ErrorLoadProjectFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read {0} project file: invalid file format..
        /// </summary>
        public static string ErrorLoadProjectInvalidProjectFile {
            get {
                return ResourceManager.GetString("ErrorLoadProjectInvalidProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the project file because an error has occured why reading the file: {0}.
        /// </summary>
        public static string ErrorLoadProjectIOError {
            get {
                return ResourceManager.GetString("ErrorLoadProjectIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the project file: access is denied..
        /// </summary>
        public static string ErrorLoadProjectUnauthorizedFileAccess {
            get {
                return ResourceManager.GetString("ErrorLoadProjectUnauthorizedFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify login.
        /// </summary>
        public static string ErrorLoginVerificationFailed {
            get {
                return ResourceManager.GetString("ErrorLoginVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscription plan has been found.
        /// </summary>
        public static string ErrorNoSubscriptionAvailable {
            get {
                return ResourceManager.GetString("ErrorNoSubscriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not specified.
        /// </summary>
        public static string ErrorPasswordNotSpecified {
            get {
                return ResourceManager.GetString("ErrorPasswordNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is missing.
        /// </summary>
        public static string ErrorProductIsMissing {
            get {
                return ResourceManager.GetString("ErrorProductIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired.
        /// </summary>
        public static string ErrorSessionExpired {
            get {
                return ResourceManager.GetString("ErrorSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current subscription has expired.
        /// </summary>
        public static string ErrorSubscriptionExpired {
            get {
                return ResourceManager.GetString("ErrorSubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current trial subscriptioin has expired.
        /// </summary>
        public static string ErrorTrialSubscriptionExpired {
            get {
                return ResourceManager.GetString("ErrorTrialSubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string LabelDatabase {
            get {
                return ResourceManager.GetString("LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources.
        /// </summary>
        public static string LabelDataSources {
            get {
                return ResourceManager.GetString("LabelDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string LabelFunction {
            get {
                return ResourceManager.GetString("LabelFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string LabelHostname {
            get {
                return ResourceManager.GetString("LabelHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical.
        /// </summary>
        public static string LabelIdentical {
            get {
                return ResourceManager.GetString("LabelIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Collate.
        /// </summary>
        public static string LabelIgnoreCollate {
            get {
                return ResourceManager.GetString("LabelIgnoreCollate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore source table column order.
        /// </summary>
        public static string LabelIgnoreReferenceTableColumnOrder {
            get {
                return ResourceManager.GetString("LabelIgnoreReferenceTableColumnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In both, but different.
        /// </summary>
        public static string LabelInBothButDifferent {
            get {
                return ResourceManager.GetString("LabelInBothButDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        public static string LabelLogLevel {
            get {
                return ResourceManager.GetString("LabelLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in Source.
        /// </summary>
        public static string LabelOnlyInSource {
            get {
                return ResourceManager.GetString("LabelOnlyInSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in Target.
        /// </summary>
        public static string LabelOnlyInTarget {
            get {
                return ResourceManager.GetString("LabelOnlyInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LabelOptions {
            get {
                return ResourceManager.GetString("LabelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order columns alphabetically.
        /// </summary>
        public static string LabelOrderColumnAlphabetically {
            get {
                return ResourceManager.GetString("LabelOrderColumnAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner mapping.
        /// </summary>
        public static string LabelOwnerMapping {
            get {
                return ResourceManager.GetString("LabelOwnerMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string LabelRecentProjects {
            get {
                return ResourceManager.GetString("LabelRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string LabelSequence {
            get {
                return ResourceManager.GetString("LabelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string LabelSource {
            get {
                return ResourceManager.GetString("LabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure.
        /// </summary>
        public static string LabelStoredProcedure {
            get {
                return ResourceManager.GetString("LabelStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string LabelTable {
            get {
                return ResourceManager.GetString("LabelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table mapping.
        /// </summary>
        public static string LabelTableMapping {
            get {
                return ResourceManager.GetString("LabelTableMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string LabelTarget {
            get {
                return ResourceManager.GetString("LabelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string LabelTrigger {
            get {
                return ResourceManager.GetString("LabelTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Data Type.
        /// </summary>
        public static string LabelUserDefinedType {
            get {
                return ResourceManager.GetString("LabelUserDefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use schema name.
        /// </summary>
        public static string LabelUseSchemaName {
            get {
                return ResourceManager.GetString("LabelUseSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string LabelUseSSL {
            get {
                return ResourceManager.GetString("LabelUseSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        public static string LabelUseWindowsAuthentication {
            get {
                return ResourceManager.GetString("LabelUseWindowsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string LabelView {
            get {
                return ResourceManager.GetString("LabelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        public static string MenuCloseProject {
            get {
                return ResourceManager.GetString("MenuCloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string MenuCompare {
            get {
                return ResourceManager.GetString("MenuCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEditProject {
            get {
                return ResourceManager.GetString("MenuEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string MenuNewProject {
            get {
                return ResourceManager.GetString("MenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string MenuOpenProject {
            get {
                return ResourceManager.GetString("MenuOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MenuProject {
            get {
                return ResourceManager.GetString("MenuProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string MenuSaveProject {
            get {
                return ResourceManager.GetString("MenuSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project As.
        /// </summary>
        public static string MenuSaveProjectAs {
            get {
                return ResourceManager.GetString("MenuSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string NotificationNewVersionAvailable {
            get {
                return ResourceManager.GetString("NotificationNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version v{0} has been released, please visit the TiCodeX website to download it..
        /// </summary>
        public static string NotificationNewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NotificationNewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version v{0} is available and ready to be installed..
        /// </summary>
        public static string NotificationUpdateReadyToBeInstalled {
            get {
                return ResourceManager.GetString("NotificationUpdateReadyToBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        public static string TitleLoginError {
            get {
                return ResourceManager.GetString("TitleLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
    }
}
