//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiCodeX.SQLSchemaCompare.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiCodeX.SQLSchemaCompare.Services.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Now.
        /// </summary>
        public static string ButtonCompareNow {
            get {
                return ResourceManager.GetString("ButtonCompareNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string ButtonNewProject {
            get {
                return ResourceManager.GetString("ButtonNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string ButtonOpenProject {
            get {
                return ResourceManager.GetString("ButtonOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string ButtonPrev {
            get {
                return ResourceManager.GetString("ButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ButtonQuit {
            get {
                return ResourceManager.GetString("ButtonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string ButtonSendFeedback {
            get {
                return ResourceManager.GetString("ButtonSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update and restart.
        /// </summary>
        public static string ButtonUpdateAndRestart {
            get {
                return ResourceManager.GetString("ButtonUpdateAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked.
        /// </summary>
        public static string ErrorAccountLocked {
            get {
                return ResourceManager.GetString("ErrorAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is available. Please update it..
        /// </summary>
        public static string ErrorApplicationUpdateNeeded {
            get {
                return ResourceManager.GetString("ErrorApplicationUpdateNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the project.
        /// </summary>
        public static string ErrorCannotCloseProject {
            get {
                return ResourceManager.GetString("ErrorCannotCloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact TiCodeX website:.
        /// </summary>
        public static string ErrorCannotContactTiCodeXWebsite {
            get {
                return ResourceManager.GetString("ErrorCannotContactTiCodeXWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new project.
        /// </summary>
        public static string ErrorCannotCreateNewProject {
            get {
                return ResourceManager.GetString("ErrorCannotCreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the project: {0}.
        /// </summary>
        public static string ErrorCannotSaveProject {
            get {
                return ResourceManager.GetString("ErrorCannotSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send the feedback.
        /// </summary>
        public static string ErrorCannotSendFeedback {
            get {
                return ResourceManager.GetString("ErrorCannotSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot exceed 2500 characters.
        /// </summary>
        public static string ErrorCommentMustBe2500Max {
            get {
                return ResourceManager.GetString("ErrorCommentMustBe2500Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not specified.
        /// </summary>
        public static string ErrorEmailNotSpecified {
            get {
                return ResourceManager.GetString("ErrorEmailNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail not verified.
        /// </summary>
        public static string ErrorEmailNotVerified {
            get {
                return ResourceManager.GetString("ErrorEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No objects found, both databases are empty.
        /// </summary>
        public static string ErrorEmptyDatabases {
            get {
                return ResourceManager.GetString("ErrorEmptyDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feedback is invalid.
        /// </summary>
        public static string ErrorInvalidFeedback {
            get {
                return ResourceManager.GetString("ErrorInvalidFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ErrorInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the file: {0}.
        /// </summary>
        public static string ErrorLoadProject {
            get {
                return ResourceManager.GetString("ErrorLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load project file: file not found..
        /// </summary>
        public static string ErrorLoadProjectFileNotFound {
            get {
                return ResourceManager.GetString("ErrorLoadProjectFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read {0} project file: invalid file format..
        /// </summary>
        public static string ErrorLoadProjectInvalidProjectFile {
            get {
                return ResourceManager.GetString("ErrorLoadProjectInvalidProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the project file because an error has occurred while reading the file: {0}.
        /// </summary>
        public static string ErrorLoadProjectIOError {
            get {
                return ResourceManager.GetString("ErrorLoadProjectIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the project file: access is denied..
        /// </summary>
        public static string ErrorLoadProjectUnauthorizedFileAccess {
            get {
                return ResourceManager.GetString("ErrorLoadProjectUnauthorizedFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify login.
        /// </summary>
        public static string ErrorLoginVerificationFailed {
            get {
                return ResourceManager.GetString("ErrorLoginVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither a rating or a comment has been specified.
        /// </summary>
        public static string ErrorNoFeedbackSpecified {
            get {
                return ResourceManager.GetString("ErrorNoFeedbackSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscription plan has been found.
        /// </summary>
        public static string ErrorNoSubscriptionAvailable {
            get {
                return ResourceManager.GetString("ErrorNoSubscriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled.
        /// </summary>
        public static string ErrorOperationCanceled {
            get {
                return ResourceManager.GetString("ErrorOperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was not executed.
        /// </summary>
        public static string ErrorOperationNotExecuted {
            get {
                return ResourceManager.GetString("ErrorOperationNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not specified.
        /// </summary>
        public static string ErrorPasswordNotSpecified {
            get {
                return ResourceManager.GetString("ErrorPasswordNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is missing.
        /// </summary>
        public static string ErrorProductIsMissing {
            get {
                return ResourceManager.GetString("ErrorProductIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired.
        /// </summary>
        public static string ErrorSessionExpired {
            get {
                return ResourceManager.GetString("ErrorSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current subscription has expired.
        /// </summary>
        public static string ErrorSubscriptionExpired {
            get {
                return ResourceManager.GetString("ErrorSubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current trial subscription has expired.
        /// </summary>
        public static string ErrorTrialSubscriptionExpired {
            get {
                return ResourceManager.GetString("ErrorTrialSubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0} settings from {1}.
        /// </summary>
        public static string ErrorUnableToReadAppSettings {
            get {
                return ResourceManager.GetString("ErrorUnableToReadAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The swiss army knife for database schema comparison and synchronization which runs on multiple OS and supports multiple databases..
        /// </summary>
        public static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AND Clause.
        /// </summary>
        public static string LabelAddANDClause {
            get {
                return ResourceManager.GetString("LabelAddANDClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add OR Clause.
        /// </summary>
        public static string LabelAddORClause {
            get {
                return ResourceManager.GetString("LabelAddORClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All objects.
        /// </summary>
        public static string LabelAllObjects {
            get {
                return ResourceManager.GetString("LabelAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic renewal.
        /// </summary>
        public static string LabelAutoRenewal {
            get {
                return ResourceManager.GetString("LabelAutoRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        public static string LabelBeginsWith {
            get {
                return ResourceManager.GetString("LabelBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string LabelComment {
            get {
                return ResourceManager.GetString("LabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint.
        /// </summary>
        public static string LabelConstraint {
            get {
                return ResourceManager.GetString("LabelConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraints.
        /// </summary>
        public static string LabelConstraints {
            get {
                return ResourceManager.GetString("LabelConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string LabelContains {
            get {
                return ResourceManager.GetString("LabelContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch left and right connection settings.
        /// </summary>
        public static string LabelCopySettingsExchange {
            get {
                return ResourceManager.GetString("LabelCopySettingsExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy connection settings left.
        /// </summary>
        public static string LabelCopySettingsLeft {
            get {
                return ResourceManager.GetString("LabelCopySettingsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy connection settings right.
        /// </summary>
        public static string LabelCopySettingsRight {
            get {
                return ResourceManager.GetString("LabelCopySettingsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Project.
        /// </summary>
        public static string LabelCreateNewProjects {
            get {
                return ResourceManager.GetString("LabelCreateNewProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string LabelDatabase {
            get {
                return ResourceManager.GetString("LabelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison of Databases.
        /// </summary>
        public static string LabelDatabaseComparison {
            get {
                return ResourceManager.GetString("LabelDatabaseComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The databases are identical.
        /// </summary>
        public static string LabelDatabasesAreIdentical {
            get {
                return ResourceManager.GetString("LabelDatabasesAreIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources.
        /// </summary>
        public static string LabelDataSources {
            get {
                return ResourceManager.GetString("LabelDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string LabelDisabled {
            get {
                return ResourceManager.GetString("LabelDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exist.
        /// </summary>
        public static string LabelDoesNotExist {
            get {
                return ResourceManager.GetString("LabelDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string LabelEnabled {
            get {
                return ResourceManager.GetString("LabelEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string LabelEndsWith {
            get {
                return ResourceManager.GetString("LabelEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string LabelEquals {
            get {
                return ResourceManager.GetString("LabelEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string LabelExcluded {
            get {
                return ResourceManager.GetString("LabelExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string LabelExpirationDate {
            get {
                return ResourceManager.GetString("LabelExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database objects matching the filter conditions will be.
        /// </summary>
        public static string LabelFilterMatchCondition {
            get {
                return ResourceManager.GetString("LabelFilterMatchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string LabelFilters {
            get {
                return ResourceManager.GetString("LabelFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key.
        /// </summary>
        public static string LabelForeignKey {
            get {
                return ResourceManager.GetString("LabelForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Keys.
        /// </summary>
        public static string LabelForeignKeys {
            get {
                return ResourceManager.GetString("LabelForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string LabelFunction {
            get {
                return ResourceManager.GetString("LabelFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string LabelFunctions {
            get {
                return ResourceManager.GetString("LabelFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histories.
        /// </summary>
        public static string LabelHistories {
            get {
                return ResourceManager.GetString("LabelHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string LabelHistory {
            get {
                return ResourceManager.GetString("LabelHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string LabelHostname {
            get {
                return ResourceManager.GetString("LabelHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical.
        /// </summary>
        public static string LabelIdentical {
            get {
                return ResourceManager.GetString("LabelIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Collation.
        /// </summary>
        public static string LabelIgnoreCollate {
            get {
                return ResourceManager.GetString("LabelIgnoreCollate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Collations on character data type columns when comparing databases..
        /// </summary>
        public static string LabelIgnoreCollateDescription {
            get {
                return ResourceManager.GetString("LabelIgnoreCollateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore source table column order.
        /// </summary>
        public static string LabelIgnoreReferenceTableColumnOrder {
            get {
                return ResourceManager.GetString("LabelIgnoreReferenceTableColumnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the comparison the column order of the target table is reordered referencing the order in the source.
        ///
        ///This option will ignore the matching and use the same order as when it was created..
        /// </summary>
        public static string LabelIgnoreReferenceTableColumnOrderDescription {
            get {
                return ResourceManager.GetString("LabelIgnoreReferenceTableColumnOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Server Certificate.
        /// </summary>
        public static string LabelIgnoreServerCertificate {
            get {
                return ResourceManager.GetString("LabelIgnoreServerCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In both, but different.
        /// </summary>
        public static string LabelInBothButDifferent {
            get {
                return ResourceManager.GetString("LabelInBothButDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        public static string LabelIncluded {
            get {
                return ResourceManager.GetString("LabelIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string LabelIndex {
            get {
                return ResourceManager.GetString("LabelIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        public static string LabelIndexes {
            get {
                return ResourceManager.GetString("LabelIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LabelLicense {
            get {
                return ResourceManager.GetString("LabelLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        public static string LabelLogLevel {
            get {
                return ResourceManager.GetString("LabelLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Database Objects.
        /// </summary>
        public static string LabelMappingDatabaseObjects {
            get {
                return ResourceManager.GetString("LabelMappingDatabaseObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Script.
        /// </summary>
        public static string LabelMigrationScript {
            get {
                return ResourceManager.GetString("LabelMigrationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly payment.
        /// </summary>
        public static string LabelMonthlyPayment {
            get {
                return ResourceManager.GetString("LabelMonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New MariaDB Project.
        /// </summary>
        public static string LabelNewMariaDbProject {
            get {
                return ResourceManager.GetString("LabelNewMariaDbProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Microsoft SQL Server Project.
        /// </summary>
        public static string LabelNewMicrosoftSQLServerProject {
            get {
                return ResourceManager.GetString("LabelNewMicrosoftSQLServerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New MySql Project.
        /// </summary>
        public static string LabelNewMySqlProject {
            get {
                return ResourceManager.GetString("LabelNewMySqlProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PostgreSQL Project.
        /// </summary>
        public static string LabelNewPostgreSQLProject {
            get {
                return ResourceManager.GetString("LabelNewPostgreSQLProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project....
        /// </summary>
        public static string LabelNewProject {
            get {
                return ResourceManager.GetString("LabelNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t begin with.
        /// </summary>
        public static string LabelNotBeginsWith {
            get {
                return ResourceManager.GetString("LabelNotBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t contain.
        /// </summary>
        public static string LabelNotContains {
            get {
                return ResourceManager.GetString("LabelNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t end with.
        /// </summary>
        public static string LabelNotEndsWith {
            get {
                return ResourceManager.GetString("LabelNotEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t equal.
        /// </summary>
        public static string LabelNotEquals {
            get {
                return ResourceManager.GetString("LabelNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        public static string LabelObjectType {
            get {
                return ResourceManager.GetString("LabelObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in Source.
        /// </summary>
        public static string LabelOnlyInSource {
            get {
                return ResourceManager.GetString("LabelOnlyInSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in Target.
        /// </summary>
        public static string LabelOnlyInTarget {
            get {
                return ResourceManager.GetString("LabelOnlyInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string LabelOpen {
            get {
                return ResourceManager.GetString("LabelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string LabelOperator {
            get {
                return ResourceManager.GetString("LabelOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string LabelOptions {
            get {
                return ResourceManager.GetString("LabelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order columns alphabetically.
        /// </summary>
        public static string LabelOrderColumnAlphabetically {
            get {
                return ResourceManager.GetString("LabelOrderColumnAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder the columns alphabetically to ignore differences of tables created with a different order..
        /// </summary>
        public static string LabelOrderColumnAlphabeticallyDescription {
            get {
                return ResourceManager.GetString("LabelOrderColumnAlphabeticallyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string LabelPeriod {
            get {
                return ResourceManager.GetString("LabelPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string LabelPeriods {
            get {
                return ResourceManager.GetString("LabelPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpetual.
        /// </summary>
        public static string LabelPerpetualPayment {
            get {
                return ResourceManager.GetString("LabelPerpetualPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key.
        /// </summary>
        public static string LabelPrimaryKey {
            get {
                return ResourceManager.GetString("LabelPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Keys.
        /// </summary>
        public static string LabelPrimaryKeys {
            get {
                return ResourceManager.GetString("LabelPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string LabelProperty {
            get {
                return ResourceManager.GetString("LabelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string LabelRating {
            get {
                return ResourceManager.GetString("LabelRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string LabelRecentProjects {
            get {
                return ResourceManager.GetString("LabelRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Keys referencing this table.
        /// </summary>
        public static string LabelReferencingForeignKeys {
            get {
                return ResourceManager.GetString("LabelReferencingForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining days.
        /// </summary>
        public static string LabelRemainingDays {
            get {
                return ResourceManager.GetString("LabelRemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal date.
        /// </summary>
        public static string LabelRenewalDate {
            get {
                return ResourceManager.GetString("LabelRenewalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve the Source Database.
        /// </summary>
        public static string LabelRetrieveSourceDatabase {
            get {
                return ResourceManager.GetString("LabelRetrieveSourceDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve the Target Database.
        /// </summary>
        public static string LabelRetrieveTargetDatabase {
            get {
                return ResourceManager.GetString("LabelRetrieveTargetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        public static string LabelSavePassword {
            get {
                return ResourceManager.GetString("LabelSavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string LabelSchema {
            get {
                return ResourceManager.GetString("LabelSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        public static string LabelSchemas {
            get {
                return ResourceManager.GetString("LabelSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string LabelSequence {
            get {
                return ResourceManager.GetString("LabelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        public static string LabelSequences {
            get {
                return ResourceManager.GetString("LabelSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string LabelSource {
            get {
                return ResourceManager.GetString("LabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Schema Compare Project.
        /// </summary>
        public static string LabelSQLSchemaCompareProjectFile {
            get {
                return ResourceManager.GetString("LabelSQLSchemaCompareProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL View.
        /// </summary>
        public static string LabelSQLView {
            get {
                return ResourceManager.GetString("LabelSQLView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure.
        /// </summary>
        public static string LabelStoredProcedure {
            get {
                return ResourceManager.GetString("LabelStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        public static string LabelStoredProcedures {
            get {
                return ResourceManager.GetString("LabelStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string LabelSubscription {
            get {
                return ResourceManager.GetString("LabelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string LabelSubscriptionPlan {
            get {
                return ResourceManager.GetString("LabelSubscriptionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string LabelSubscriptionPro {
            get {
                return ResourceManager.GetString("LabelSubscriptionPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string LabelSubscriptionTrial {
            get {
                return ResourceManager.GetString("LabelSubscriptionTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string LabelTable {
            get {
                return ResourceManager.GetString("LabelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string LabelTables {
            get {
                return ResourceManager.GetString("LabelTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string LabelTarget {
            get {
                return ResourceManager.GetString("LabelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string LabelTrigger {
            get {
                return ResourceManager.GetString("LabelTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        public static string LabelTriggers {
            get {
                return ResourceManager.GetString("LabelTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrades until.
        /// </summary>
        public static string LabelUpgradesUntil {
            get {
                return ResourceManager.GetString("LabelUpgradesUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Azure Authentication.
        /// </summary>
        public static string LabelUseAzureAuthentication {
            get {
                return ResourceManager.GetString("LabelUseAzureAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Data Type.
        /// </summary>
        public static string LabelUserDefinedType {
            get {
                return ResourceManager.GetString("LabelUserDefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Data Types.
        /// </summary>
        public static string LabelUserDefinedTypes {
            get {
                return ResourceManager.GetString("LabelUserDefinedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string LabelUseSSL {
            get {
                return ResourceManager.GetString("LabelUseSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        public static string LabelUseWindowsAuthentication {
            get {
                return ResourceManager.GetString("LabelUseWindowsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LabelValue {
            get {
                return ResourceManager.GetString("LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string LabelView {
            get {
                return ResourceManager.GetString("LabelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string LabelViews {
            get {
                return ResourceManager.GetString("LabelViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string LabelWebsite {
            get {
                return ResourceManager.GetString("LabelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly payment.
        /// </summary>
        public static string LabelYearlyPayment {
            get {
                return ResourceManager.GetString("LabelYearlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        public static string MenuCloseProject {
            get {
                return ResourceManager.GetString("MenuCloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string MenuCompare {
            get {
                return ResourceManager.GetString("MenuCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact support (support@ticodex.com).
        /// </summary>
        public static string MenuContactSupport {
            get {
                return ResourceManager.GetString("MenuContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer tools.
        /// </summary>
        public static string MenuDeveloperTools {
            get {
                return ResourceManager.GetString("MenuDeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string MenuEditProject {
            get {
                return ResourceManager.GetString("MenuEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string MenuFind {
            get {
                return ResourceManager.GetString("MenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Migration Script.
        /// </summary>
        public static string MenuFullMigrationScript {
            get {
                return ResourceManager.GetString("MenuFullMigrationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Source Database Script.
        /// </summary>
        public static string MenuFullSourceDatabaseScript {
            get {
                return ResourceManager.GetString("MenuFullSourceDatabaseScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Target Database Script.
        /// </summary>
        public static string MenuFullTargetDatabaseScript {
            get {
                return ResourceManager.GetString("MenuFullTargetDatabaseScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Script.
        /// </summary>
        public static string MenuGenerateScript {
            get {
                return ResourceManager.GetString("MenuGenerateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Line....
        /// </summary>
        public static string MenuGoToLine {
            get {
                return ResourceManager.GetString("MenuGoToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage profile.
        /// </summary>
        public static string MenuManageProfile {
            get {
                return ResourceManager.GetString("MenuManageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string MenuNewProject {
            get {
                return ResourceManager.GetString("MenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        public static string MenuOpenLogsFolder {
            get {
                return ResourceManager.GetString("MenuOpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string MenuOpenProject {
            get {
                return ResourceManager.GetString("MenuOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MenuProject {
            get {
                return ResourceManager.GetString("MenuProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string MenuSaveProject {
            get {
                return ResourceManager.GetString("MenuSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project As.
        /// </summary>
        public static string MenuSaveProjectAs {
            get {
                return ResourceManager.GetString("MenuSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show line numbers.
        /// </summary>
        public static string MenuShowLineNumbers {
            get {
                return ResourceManager.GetString("MenuShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string MenuSignOut {
            get {
                return ResourceManager.GetString("MenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort the operation?.
        /// </summary>
        public static string MessageConfirmAbortOperation {
            get {
                return ResourceManager.GetString("MessageConfirmAbortOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest version.
        /// </summary>
        public static string MessageDownloadLatestVersion {
            get {
                return ResourceManager.GetString("MessageDownloadLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes to the opened project?.
        /// </summary>
        public static string MessageDoYouWantToSaveProjectChanges {
            get {
                return ResourceManager.GetString("MessageDoYouWantToSaveProjectChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a subscription.
        /// </summary>
        public static string MessageGetASubscription {
            get {
                return ResourceManager.GetString("MessageGetASubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has been saved..
        /// </summary>
        public static string MessageProjectSavedSuccessfully {
            get {
                return ResourceManager.GetString("MessageProjectSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback!.
        /// </summary>
        public static string MessageThanksForFeedback {
            get {
                return ResourceManager.GetString("MessageThanksForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string NotificationNewVersionAvailable {
            get {
                return ResourceManager.GetString("NotificationNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version v{0} has been released, please visit the TiCodeX website to download it..
        /// </summary>
        public static string NotificationNewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NotificationNewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version v{0} is available and ready to be installed..
        /// </summary>
        public static string NotificationUpdateReadyToBeInstalled {
            get {
                return ResourceManager.GetString("NotificationUpdateReadyToBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Constraints....
        /// </summary>
        public static string StatusComparingConstraints {
            get {
                return ResourceManager.GetString("StatusComparingConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing User-Defined Data Types....
        /// </summary>
        public static string StatusComparingDataTypes {
            get {
                return ResourceManager.GetString("StatusComparingDataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Foreign Keys....
        /// </summary>
        public static string StatusComparingForeignKeys {
            get {
                return ResourceManager.GetString("StatusComparingForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Functions....
        /// </summary>
        public static string StatusComparingFunctions {
            get {
                return ResourceManager.GetString("StatusComparingFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Indexes....
        /// </summary>
        public static string StatusComparingIndexes {
            get {
                return ResourceManager.GetString("StatusComparingIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Schemas....
        /// </summary>
        public static string StatusComparingSchemas {
            get {
                return ResourceManager.GetString("StatusComparingSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Sequences....
        /// </summary>
        public static string StatusComparingSequences {
            get {
                return ResourceManager.GetString("StatusComparingSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Stored Procedures....
        /// </summary>
        public static string StatusComparingStoredProcedures {
            get {
                return ResourceManager.GetString("StatusComparingStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Tables....
        /// </summary>
        public static string StatusComparingTables {
            get {
                return ResourceManager.GetString("StatusComparingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Triggers....
        /// </summary>
        public static string StatusComparingTriggers {
            get {
                return ResourceManager.GetString("StatusComparingTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Views....
        /// </summary>
        public static string StatusComparingViews {
            get {
                return ResourceManager.GetString("StatusComparingViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server....
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Constraints....
        /// </summary>
        public static string StatusMappingConstraints {
            get {
                return ResourceManager.GetString("StatusMappingConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping User-Defined Data Types....
        /// </summary>
        public static string StatusMappingDataTypes {
            get {
                return ResourceManager.GetString("StatusMappingDataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Foreign Keys....
        /// </summary>
        public static string StatusMappingForeignKeys {
            get {
                return ResourceManager.GetString("StatusMappingForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Functions....
        /// </summary>
        public static string StatusMappingFunctions {
            get {
                return ResourceManager.GetString("StatusMappingFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Indexes....
        /// </summary>
        public static string StatusMappingIndexes {
            get {
                return ResourceManager.GetString("StatusMappingIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Schemas....
        /// </summary>
        public static string StatusMappingSchemas {
            get {
                return ResourceManager.GetString("StatusMappingSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Sequences....
        /// </summary>
        public static string StatusMappingSequences {
            get {
                return ResourceManager.GetString("StatusMappingSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Stored Procedures....
        /// </summary>
        public static string StatusMappingStoredProcedures {
            get {
                return ResourceManager.GetString("StatusMappingStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Tables....
        /// </summary>
        public static string StatusMappingTables {
            get {
                return ResourceManager.GetString("StatusMappingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Triggers....
        /// </summary>
        public static string StatusMappingTriggers {
            get {
                return ResourceManager.GetString("StatusMappingTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Views....
        /// </summary>
        public static string StatusMappingViews {
            get {
                return ResourceManager.GetString("StatusMappingViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Constraints....
        /// </summary>
        public static string StatusRetrievingConstraints {
            get {
                return ResourceManager.GetString("StatusRetrievingConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving User-Defined Data Types....
        /// </summary>
        public static string StatusRetrievingDataTypes {
            get {
                return ResourceManager.GetString("StatusRetrievingDataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Foreign Keys....
        /// </summary>
        public static string StatusRetrievingForeignKeys {
            get {
                return ResourceManager.GetString("StatusRetrievingForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Functions....
        /// </summary>
        public static string StatusRetrievingFunctions {
            get {
                return ResourceManager.GetString("StatusRetrievingFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Indexes....
        /// </summary>
        public static string StatusRetrievingIndexes {
            get {
                return ResourceManager.GetString("StatusRetrievingIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Primary Keys....
        /// </summary>
        public static string StatusRetrievingPrimaryKeys {
            get {
                return ResourceManager.GetString("StatusRetrievingPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Schemas....
        /// </summary>
        public static string StatusRetrievingSchemas {
            get {
                return ResourceManager.GetString("StatusRetrievingSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Sequences....
        /// </summary>
        public static string StatusRetrievingSequences {
            get {
                return ResourceManager.GetString("StatusRetrievingSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Stored Procedures....
        /// </summary>
        public static string StatusRetrievingStoredProcedures {
            get {
                return ResourceManager.GetString("StatusRetrievingStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Tables....
        /// </summary>
        public static string StatusRetrievingTables {
            get {
                return ResourceManager.GetString("StatusRetrievingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Triggers....
        /// </summary>
        public static string StatusRetrievingTriggers {
            get {
                return ResourceManager.GetString("StatusRetrievingTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Views....
        /// </summary>
        public static string StatusRetrievingViews {
            get {
                return ResourceManager.GetString("StatusRetrievingViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Compare.
        /// </summary>
        public static string TitleAbortCompare {
            get {
                return ResourceManager.GetString("TitleAbortCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback sent.
        /// </summary>
        public static string TitleFeedbackSent {
            get {
                return ResourceManager.GetString("TitleFeedbackSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        public static string TitleLoginError {
            get {
                return ResourceManager.GetString("TitleLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string TitleOpenProject {
            get {
                return ResourceManager.GetString("TitleOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string TitleSaveProject {
            get {
                return ResourceManager.GetString("TitleSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
    }
}
