name: Unit Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  unit_tests:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.2xx
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test SQLSchemaCompare.Test --no-build --configuration Release --logger trx --filter Category!=IntegrationTest
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        check_name: "Unit Test Results"
        files: SQLSchemaCompare.Test/TestResults/*.trx
