name: Unit Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore dependencies
      run: dotnet restore
    - name: Install npm dependencies
      run: npm install
    - name: Build
      run: msbuild SQLSchemaCompare.sln /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --configuration Release --filter Category!=IntegrationTest
