name: Unit Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore dependencies
      run: dotnet restore
    - name: Install npm dependencies
      run: npm install
      working-directory: SQLSchemaCompare
    - name: Build
      run: msbuild SQLSchemaCompare.sln /p:Configuration=Release
    - name: Test
      run: dotnet test SQLSchemaCompare.Test --no-build --configuration Release --logger trx --filter Category!=IntegrationTest
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: TestResults/**/*.trx
